name: "Code Deploy"
on:
  push:
  workflow_call:
    
jobs:
  run_worflow:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Code Deploy Simulation"
      with:
        gh_environment: production 
    
