name: "Code Deploy"
on:
  push:
  workflow_call:
    
jobs:
  code_deploy::
    name: Code Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Print env value
      env:
        gh_environment: production
      run: |
        echo "Code Deploy Simulation - approval needed for $gh_environment"
    
