name: "Code Deploy"
on:
  push:
  workflow_call:
    
jobs:
  run_worflow:
    runs-on: ubuntu-latest
    env:
      gh_environment: production 
    steps:
    - run: |
        echo "Code Deploy Simulation - approval needed for $(( var.gh_environment }}"
    
