name: "Deploy Code"

on:
  push:
  workflow_call:
    inputs:
      gh_environment:
        description: 'Specifies the deployment environment'
        required: false
        type: string
        default: none
jobs:
  code_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.gh_environment }}
    steps:
      - name: "Deploy Code"
        run: echo "Running code deployment"
